import mimetypes
from typing import BinaryIO

from csfunctions.service.base import BaseService
from csfunctions.service.file_upload_schemas import PresignedWriteUrls
from csfunctions.service.presigned_upload import PresignedUploadMixin
from csfunctions.service.temp_file_schemas import (
    DEFAULT_MIMETYPE,
    AbortTempFileUploadRequest,
    CompleteTempFileUploadRequest,
    CreateTempFileRequest,
    CreateTempFileResponse,
)


class TempFileService(PresignedUploadMixin, BaseService):
    """
    Service for creating temporary files, e.g. to let a user download a file
    that was generated by a Function.
    """

    def _create_temp_file(
        self, filename: str, mimetype: str, filesize: int, persno: str
    ) -> tuple[str, PresignedWriteUrls]:
        """Create a new temporary file and request presigned URLs for uploading its content."""
        response_json = self.request(
            endpoint="/temp_file/create",
            method="POST",
            json=CreateTempFileRequest(
                filename=filename, mimetype=mimetype, filesize=filesize, persno=persno
            ).model_dump(),
        )
        data = CreateTempFileResponse.model_validate(response_json)
        return data.temp_file_id, data.presigned_write_urls

    def _complete_upload(self, temp_file_id: str, presigned_urls: PresignedWriteUrls, persno: str) -> None:
        """Mark the upload as complete, so the file can be downloaded."""
        self.request(
            endpoint=f"/temp_file/{temp_file_id}/complete",
            method="POST",
            json=CompleteTempFileUploadRequest(presigned_write_urls=presigned_urls, persno=persno).model_dump(),
        )

    def _abort_upload(self, temp_file_id: str, presigned_write_urls: PresignedWriteUrls, persno: str) -> None:
        """Abort an ongoing upload and delete the temporary file."""
        self.request(
            endpoint=f"/temp_file/{temp_file_id}/abort",
            method="POST",
            json=AbortTempFileUploadRequest(presigned_write_urls=presigned_write_urls, persno=persno).model_dump(),
        )

    def upload(
        self,
        stream: BinaryIO,
        filename: str,
        mimetype: str | None = None,
        persno: str | None = None,
        filesize: int | None = None,
    ) -> str:
        """
        Uploads content to a new temporary file and returns the ID of that file.
        Handles aborting the upload if an error occurs.

        Pass the returned ID to a
        [DownloadFileAction][csfunctions.actions.DownloadFileAction] to make the
        users browser download the file.

        The file can be downloaded exactly once and only by the user given in
        `persno`. It is deleted after the download.

        Args:
            stream: A binary stream containing the file data.
            filename: The name the file will have when the user downloads it.
            mimetype: The MIME type of the content. Guessed from the filename if not given.
            persno: The user/person number who will be allowed to download the file
                (default is user that triggered the Function).
            filesize: Size of the file in bytes (required only if the stream is not seekable).

        Returns:
            The ID of the newly created temporary file.

        Raises:
            csfunctions.service.Unauthorized: If the service token is invalid.
            csfunctions.service.NotFound: If the user does not exist.
            csfunctions.service.UnprocessableEntity: If the request is invalid, e.g. the file is too large.
            csfunctions.service.RateLimitExceeded: If the services rate limit is exceeded.
        """
        persno = persno or self.metadata.app_user
        if mimetype is None:
            mimetype = mimetypes.guess_type(filename)[0] or DEFAULT_MIMETYPE
        if filesize is None:
            filesize = self._get_stream_size(stream)

        temp_file_id, presigned = self._create_temp_file(
            filename=filename,
            mimetype=mimetype,
            filesize=filesize,
            persno=persno,
        )
        try:
            # the sha256 is not used, because temporary files have nowhere to store it
            presigned_with_etags, _sha256 = self._upload_from_stream(presigned_urls=presigned, stream=stream)
            self._complete_upload(
                temp_file_id=temp_file_id,
                presigned_urls=presigned_with_etags,
                persno=persno,
            )
        except Exception as e:
            # if something goes wrong during upload we try to abort, so that the
            # temporary file and its content are cleaned up right away
            self._abort_upload(
                temp_file_id=temp_file_id,
                presigned_write_urls=presigned,
                persno=persno,
            )
            raise e
        return temp_file_id
