from datetime import date, datetime
from typing import TYPE_CHECKING, Literal, Optional

from pydantic import Field

from csfunctions.util import get_items_of_type

from .base import BaseObject, ObjectType
from .file import File
from .part import Part

if TYPE_CHECKING:
    from csfunctions.events import EventData


class Document(BaseObject):
    """
    Normal Document that doesn't contain a CAD-Model.
    """

    object_type: Literal[ObjectType.DOCUMENT] = ObjectType.DOCUMENT

    z_nummer: str = Field(..., description="document number")
    z_index: str = Field(..., description="index")
    titel: str | None = Field(..., description="title")
    category1_name_en: str | None = Field(..., description="Main Category")
    category1_name_de: str | None = Field(..., description="Main Category")
    category2_name_en: str | None = Field(..., description="Category")
    category2_name_de: str | None = Field(..., description="Category")
    z_categ1: str | None = Field(..., description="Main Category")
    z_categ2: str | None = Field(..., description="Category")
    cdb_obsolete: int | None = Field(..., description="Obsolete")
    z_status: int = Field(..., description="Status Number")
    z_status_txt: str = Field(..., description="Status Text")
    autoren: str | None = Field(..., description="Authors, comma separated")
    z_bereich: str | None = Field("", description="Department.")
    z_language: str | None = Field("", description="language")
    keywords: str | None = Field("", description="Keywords")
    z_bemerkung: str | None = Field("", description="Remarks")
    joined_status_name: str | None = Field(..., description="Status")
    erzeug_system: str | None = Field("", description="Program that created the document")
    cdb_lock: str | None = Field("", description="User that locked the document.")
    mapped_cdb_lock_name: str | None = Field(None, description="Username that locked the document.")
    ce_valid_from: date | datetime | None = Field(None, description="Effective from")
    ce_valid_to: date | datetime | None = Field(None, description="Effective to")
    cdb_ec_id: str | None = Field("", description="Engineering Change ID")
    ursprungs_z: str | None = Field("", description="Origin")
    teilenummer: str | None = Field("", description="Part No.")
    t_index: str | None = Field("", description="Part Index")
    cdb_project_id: str | None = Field("", description="Project No.")
    project_name: str | None = Field("", description="Project Name")
    src_name: str | None = Field("", description="Source")
    src_cdate: datetime | None = Field(None, description="Source created on")
    src_rdate: datetime | None = Field(None, description="Source received on")
    src_number: str | None = Field("", description="Original No.")
    src_index: str | None = Field("", description="Original Index")
    src_fname: str | None = Field("", description="Original Filename")
    source_oid: str | None = Field("", description="Based on Template")
    cdb_cpersno: str | None = Field("", description="Created by")
    mapped_cdb_cpersno_name: str | None = Field("", description="Created by")
    cdb_cdate: datetime | None = Field(None, description="Created on")
    cdb_mpersno: str | None = Field("", description="Last Modified by")
    mapped_cdb_mpersno_name: str | None = Field("", description="Last Modified by")
    cdb_mdate: datetime | None = Field(None, description="Last Modified on")
    cdb_m2persno: str | None = Field("", description="File Last Saved by")
    mapped_cdb_m2persno_name: str | None = Field("", description="File Last Saved by")
    cdb_m2date: datetime | None = Field(None, description="File Last Saved on")
    z_art: str | None = Field(None, description="Document Type")
    mapped_materialnr_erp: str | None = Field(None, description="Materialnumber ERP")
    cdb_object_id: str | None = Field(None, description="Object ID")

    # Custom Char Fields
    cca_char_doc_1: str | None = Field(None, description="Custom Char Field")
    cca_char_doc_2: str | None = Field(None, description="Custom Char Field")
    cca_char_doc_3: str | None = Field(None, description="Custom Char Field")
    cca_char_doc_4: str | None = Field(None, description="Custom Char Field")
    cca_char_doc_5: str | None = Field(None, description="Custom Char Field")
    cca_char_doc_6: str | None = Field(None, description="Custom Char Field")
    cca_char_doc_7: str | None = Field(None, description="Custom Char Field")
    cca_char_doc_8: str | None = Field(None, description="Custom Char Field")
    cca_char_doc_9: str | None = Field(None, description="Custom Char Field")
    cca_char_doc_10: str | None = Field(None, description="Custom Char Field")
    cca_char_doc_11: str | None = Field(None, description="Custom Char Field")
    cca_char_doc_12: str | None = Field(None, description="Custom Char Field")
    cca_char_doc_13: str | None = Field(None, description="Custom Char Field")
    cca_char_doc_14: str | None = Field(None, description="Custom Char Field")
    cca_char_doc_15: str | None = Field(None, description="Custom Char Field")
    cca_char_doc_16: str | None = Field(None, description="Custom Char Field")
    cca_char_doc_17: str | None = Field(None, description="Custom Char Field")
    cca_char_doc_18: str | None = Field(None, description="Custom Char Field")
    cca_char_doc_19: str | None = Field(None, description="Custom Char Field")
    cca_char_doc_20: str | None = Field(None, description="Custom Char Field")
    # Custom Integer Fields
    cca_integer_doc_1: int | None = Field(None, description="Custom Integer Field")
    cca_integer_doc_2: int | None = Field(None, description="Custom Integer Field")
    cca_integer_doc_3: int | None = Field(None, description="Custom Integer Field")
    cca_integer_doc_4: int | None = Field(None, description="Custom Integer Field")
    cca_integer_doc_5: int | None = Field(None, description="Custom Integer Field")
    cca_integer_doc_6: int | None = Field(None, description="Custom Integer Field")
    cca_integer_doc_7: int | None = Field(None, description="Custom Integer Field")
    cca_integer_doc_8: int | None = Field(None, description="Custom Integer Field")
    cca_integer_doc_9: int | None = Field(None, description="Custom Integer Field")
    cca_integer_doc_10: int | None = Field(None, description="Custom Integer Field")
    cca_integer_doc_11: int | None = Field(None, description="Custom Integer Field")
    cca_integer_doc_12: int | None = Field(None, description="Custom Integer Field")
    cca_integer_doc_13: int | None = Field(None, description="Custom Integer Field")
    cca_integer_doc_14: int | None = Field(None, description="Custom Integer Field")
    cca_integer_doc_15: int | None = Field(None, description="Custom Integer Field")
    cca_integer_doc_16: int | None = Field(None, description="Custom Integer Field")
    cca_integer_doc_17: int | None = Field(None, description="Custom Integer Field")
    cca_integer_doc_18: int | None = Field(None, description="Custom Integer Field")
    cca_integer_doc_19: int | None = Field(None, description="Custom Integer Field")
    cca_integer_doc_20: int | None = Field(None, description="Custom Integer Field")
    # Custom Float Fields
    cca_float_doc_1: float | None = Field(None, description="Custom Float Field")
    cca_float_doc_2: float | None = Field(None, description="Custom Float Field")
    cca_float_doc_3: float | None = Field(None, description="Custom Float Field")
    cca_float_doc_4: float | None = Field(None, description="Custom Float Field")
    cca_float_doc_5: float | None = Field(None, description="Custom Float Field")
    cca_float_doc_6: float | None = Field(None, description="Custom Float Field")
    cca_float_doc_7: float | None = Field(None, description="Custom Float Field")
    cca_float_doc_8: float | None = Field(None, description="Custom Float Field")
    cca_float_doc_9: float | None = Field(None, description="Custom Float Field")
    cca_float_doc_10: float | None = Field(None, description="Custom Float Field")
    cca_float_doc_11: float | None = Field(None, description="Custom Float Field")
    cca_float_doc_12: float | None = Field(None, description="Custom Float Field")
    cca_float_doc_13: float | None = Field(None, description="Custom Float Field")
    cca_float_doc_14: float | None = Field(None, description="Custom Float Field")
    cca_float_doc_15: float | None = Field(None, description="Custom Float Field")
    cca_float_doc_16: float | None = Field(None, description="Custom Float Field")
    cca_float_doc_17: float | None = Field(None, description="Custom Float Field")
    cca_float_doc_18: float | None = Field(None, description="Custom Float Field")
    cca_float_doc_19: float | None = Field(None, description="Custom Float Field")
    cca_float_doc_20: float | None = Field(None, description="Custom Float Field")
    # Custom Date Fields
    cca_date_doc_2: datetime | None = Field(None, description="Custom Date Field")
    cca_date_doc_3: datetime | None = Field(None, description="Custom Date Field")
    cca_date_doc_4: datetime | None = Field(None, description="Custom Date Field")
    cca_date_doc_5: datetime | None = Field(None, description="Custom Date Field")
    cca_date_doc_6: datetime | None = Field(None, description="Custom Date Field")
    cca_date_doc_7: datetime | None = Field(None, description="Custom Date Field")
    cca_date_doc_8: datetime | None = Field(None, description="Custom Date Field")
    cca_date_doc_9: datetime | None = Field(None, description="Custom Date Field")
    cca_date_doc_10: datetime | None = Field(None, description="Custom Date Field")
    cca_date_doc_11: datetime | None = Field(None, description="Custom Date Field")
    cca_date_doc_12: datetime | None = Field(None, description="Custom Date Field")
    cca_date_doc_13: datetime | None = Field(None, description="Custom Date Field")
    cca_date_doc_14: datetime | None = Field(None, description="Custom Date Field")
    cca_date_doc_15: datetime | None = Field(None, description="Custom Date Field")
    cca_date_doc_16: datetime | None = Field(None, description="Custom Date Field")
    cca_date_doc_17: datetime | None = Field(None, description="Custom Date Field")
    cca_date_doc_18: datetime | None = Field(None, description="Custom Date Field")
    cca_date_doc_19: datetime | None = Field(None, description="Custom Date Field")
    cca_date_doc_20: datetime | None = Field(None, description="Custom Date Field")
    cca_date_doc_1: datetime | None = Field(None, description="Custom Date Field")
    # Custom Boolean Fields
    cca_bool_doc_1: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_doc_2: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_doc_3: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_doc_4: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_doc_5: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_doc_6: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_doc_7: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_doc_8: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_doc_9: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_doc_10: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_doc_11: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_doc_12: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_doc_13: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_doc_14: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_doc_15: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_doc_16: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_doc_17: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_doc_18: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_doc_19: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_doc_20: bool | None = Field(None, description="Custom Boolean Field")
    # Custom BigChar Fields
    cca_bigchar_doc_1: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_doc_2: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_doc_3: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_doc_4: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_doc_5: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_doc_6: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_doc_7: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_doc_8: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_doc_9: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_doc_10: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_doc_11: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_doc_12: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_doc_13: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_doc_14: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_doc_15: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_doc_16: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_doc_17: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_doc_18: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_doc_19: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_doc_20: str | None = Field(None, description="Custom BigChar Field")
    # Custom Char Model Fields
    cca_char_model_1: str | None = Field(None, description="Custom Char Field")
    cca_char_model_2: str | None = Field(None, description="Custom Char Field")
    cca_char_model_3: str | None = Field(None, description="Custom Char Field")
    cca_char_model_4: str | None = Field(None, description="Custom Char Field")
    cca_char_model_5: str | None = Field(None, description="Custom Char Field")
    cca_char_model_6: str | None = Field(None, description="Custom Char Field")
    cca_char_model_7: str | None = Field(None, description="Custom Char Field")
    cca_char_model_8: str | None = Field(None, description="Custom Char Field")
    cca_char_model_9: str | None = Field(None, description="Custom Char Field")
    cca_char_model_10: str | None = Field(None, description="Custom Char Field")
    cca_char_model_11: str | None = Field(None, description="Custom Char Field")
    cca_char_model_12: str | None = Field(None, description="Custom Char Field")
    cca_char_model_13: str | None = Field(None, description="Custom Char Field")
    cca_char_model_14: str | None = Field(None, description="Custom Char Field")
    cca_char_model_15: str | None = Field(None, description="Custom Char Field")
    cca_char_model_16: str | None = Field(None, description="Custom Char Field")
    cca_char_model_17: str | None = Field(None, description="Custom Char Field")
    cca_char_model_18: str | None = Field(None, description="Custom Char Field")
    cca_char_model_19: str | None = Field(None, description="Custom Char Field")
    cca_char_model_20: str | None = Field(None, description="Custom Char Field")
    # Custom BigChar Model Fields
    cca_bigchar_model_1: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_model_2: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_model_3: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_model_4: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_model_5: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_model_6: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_model_7: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_model_8: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_model_9: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_model_10: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_model_11: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_model_12: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_model_13: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_model_14: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_model_15: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_model_16: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_model_17: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_model_18: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_model_19: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_model_20: str | None = Field(None, description="Custom BigChar Field")
    # Custom Integer Model Fields
    cca_integer_model_1: int | None = Field(None, description="Custom Integer Field")
    cca_integer_model_2: int | None = Field(None, description="Custom Integer Field")
    cca_integer_model_3: int | None = Field(None, description="Custom Integer Field")
    cca_integer_model_4: int | None = Field(None, description="Custom Integer Field")
    cca_integer_model_5: int | None = Field(None, description="Custom Integer Field")
    cca_integer_model_6: int | None = Field(None, description="Custom Integer Field")
    cca_integer_model_7: int | None = Field(None, description="Custom Integer Field")
    cca_integer_model_8: int | None = Field(None, description="Custom Integer Field")
    cca_integer_model_9: int | None = Field(None, description="Custom Integer Field")
    cca_integer_model_10: int | None = Field(None, description="Custom Integer Field")
    cca_integer_model_11: int | None = Field(None, description="Custom Integer Field")
    cca_integer_model_12: int | None = Field(None, description="Custom Integer Field")
    cca_integer_model_13: int | None = Field(None, description="Custom Integer Field")
    cca_integer_model_14: int | None = Field(None, description="Custom Integer Field")
    cca_integer_model_15: int | None = Field(None, description="Custom Integer Field")
    cca_integer_model_16: int | None = Field(None, description="Custom Integer Field")
    cca_integer_model_17: int | None = Field(None, description="Custom Integer Field")
    cca_integer_model_18: int | None = Field(None, description="Custom Integer Field")
    cca_integer_model_19: int | None = Field(None, description="Custom Integer Field")
    cca_integer_model_20: int | None = Field(None, description="Custom Integer Field")
    # Custom Float Model Fields
    cca_float_model_1: float | None = Field(None, description="Custom Float Field")
    cca_float_model_2: float | None = Field(None, description="Custom Float Field")
    cca_float_model_3: float | None = Field(None, description="Custom Float Field")
    cca_float_model_4: float | None = Field(None, description="Custom Float Field")
    cca_float_model_5: float | None = Field(None, description="Custom Float Field")
    cca_float_model_6: float | None = Field(None, description="Custom Float Field")
    cca_float_model_7: float | None = Field(None, description="Custom Float Field")
    cca_float_model_8: float | None = Field(None, description="Custom Float Field")
    cca_float_model_9: float | None = Field(None, description="Custom Float Field")
    cca_float_model_10: float | None = Field(None, description="Custom Float Field")
    cca_float_model_11: float | None = Field(None, description="Custom Float Field")
    cca_float_model_12: float | None = Field(None, description="Custom Float Field")
    cca_float_model_13: float | None = Field(None, description="Custom Float Field")
    cca_float_model_14: float | None = Field(None, description="Custom Float Field")
    cca_float_model_15: float | None = Field(None, description="Custom Float Field")
    cca_float_model_16: float | None = Field(None, description="Custom Float Field")
    cca_float_model_17: float | None = Field(None, description="Custom Float Field")
    cca_float_model_18: float | None = Field(None, description="Custom Float Field")
    cca_float_model_19: float | None = Field(None, description="Custom Float Field")
    cca_float_model_20: float | None = Field(None, description="Custom Float Field")
    # Custom Boolean Model Fields
    cca_bool_model_1: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_model_2: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_model_3: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_model_4: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_model_5: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_model_6: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_model_7: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_model_8: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_model_9: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_model_10: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_model_11: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_model_12: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_model_13: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_model_14: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_model_15: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_model_16: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_model_17: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_model_18: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_model_19: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_model_20: bool | None = Field(None, description="Custom Boolean Field")
    # Custom Date Model Fields
    cca_date_model_1: date | datetime | None = Field(None, description="Custom Date Field")
    cca_date_model_2: date | datetime | None = Field(None, description="Custom Date Field")
    cca_date_model_3: date | datetime | None = Field(None, description="Custom Date Field")
    cca_date_model_4: date | datetime | None = Field(None, description="Custom Date Field")
    cca_date_model_5: date | datetime | None = Field(None, description="Custom Date Field")
    cca_date_model_6: date | datetime | None = Field(None, description="Custom Date Field")
    cca_date_model_7: date | datetime | None = Field(None, description="Custom Date Field")
    cca_date_model_8: date | datetime | None = Field(None, description="Custom Date Field")
    cca_date_model_9: date | datetime | None = Field(None, description="Custom Date Field")
    cca_date_model_10: date | datetime | None = Field(None, description="Custom Date Field")
    cca_date_model_11: date | datetime | None = Field(None, description="Custom Date Field")
    cca_date_model_12: date | datetime | None = Field(None, description="Custom Date Field")
    cca_date_model_13: date | datetime | None = Field(None, description="Custom Date Field")
    cca_date_model_14: date | datetime | None = Field(None, description="Custom Date Field")
    cca_date_model_15: date | datetime | None = Field(None, description="Custom Date Field")
    cca_date_model_16: date | datetime | None = Field(None, description="Custom Date Field")
    cca_date_model_17: date | datetime | None = Field(None, description="Custom Date Field")
    cca_date_model_18: date | datetime | None = Field(None, description="Custom Date Field")
    cca_date_model_19: date | datetime | None = Field(None, description="Custom Date Field")
    cca_date_model_20: date | datetime | None = Field(None, description="Custom Date Field")

    files: list[File] = Field([], description="Files attached to the document")

    # in the json schema parts are transferred in parallel to documents, e.g. documents = [...], parts=[...]
    # the execute handler (csfunctions.handler.execute) attaches the parts to the documents that reference them,
    # meaning we need to exclude the part attribute from the json schema
    part: Optional["Part"] = Field(None, exclude=True)

    def link_objects(self, data: "EventData"):
        from .part import Part

        if self.teilenummer:
            parts = get_items_of_type(data, Part)
            self._link_part(parts)

    def _link_part(self, parts: list["Part"]):
        for part in parts:
            if f"{part.teilenummer}@{part.t_index}" == f"{self.teilenummer}@{self.t_index}":
                self.part = part
                return


class CADDocument(Document):
    """
    Special Document type that contains a CAD-Model.
    """

    object_type: Literal[ObjectType.CAD_DOCUMENT] = ObjectType.CAD_DOCUMENT  # type: ignore[assignment]


Part.model_rebuild()
