from datetime import date, datetime
from typing import TYPE_CHECKING, Literal, Optional

from pydantic import Field

from csfunctions.util import get_items_of_type

from .base import BaseObject, ObjectType

if TYPE_CHECKING:
    from csfunctions.events import EventData

    from .document import Document


class Part(BaseObject):
    object_type: Literal[ObjectType.PART] = ObjectType.PART

    teilenummer: str = Field(..., description="part number")
    t_index: str = Field(..., description="part index")
    status: int = Field(..., description="Status Number")
    materialnr_erp: str | None = Field(None, description="Material No. (ERP)")
    benennung: str | None = Field(None, description="Name")
    eng_benennung: str | None = Field(None, description="Name")
    benennung2: str | None = Field(None, description="Additional Name")
    t_kategorie_name_de: str | None = Field(None, description="Category Name")
    t_kategorie_name_en: str | None = Field(None, description="Category Name")
    cdb_t_project_id: str | None = Field(None, description="Project ID")
    t_bereich: str | None = Field(None, description="Department")
    cdb_t_ec_id: str | None = Field(None, description="Engineering Change ID")
    item_maturity: int | None = Field(None, description="Maturity Level")
    gebrauchsstand_name_de: str | None = Field(None, description="Usage Status")
    gebrauchsstand_name_en: str | None = Field(None, description="Usage Status")
    ce_valid_from: date | datetime | None = Field(None, description="Effective from")
    ce_valid_to: date | datetime | None = Field(None, description="Effective to")
    mengeneinheit_name_de: str | None = Field(None, description="Quantity Unit")
    mengeneinheit_name_en: str | None = Field(None, description="Quantity Unit")
    st_gewicht: Optional[float] = Field(None, description="Weight (kg)")
    material_object_id: str | None = Field(None, description="Material ID")
    surface_name_en: str | None = Field(None, description="Surface")
    surface_name_de: str | None = Field(None, description="Surface")
    techdaten: str | None = Field(None, description="Engineering Data")
    cssaas_mirrored_from: str | None = Field(None, description="Mirror Part ID")
    t_ersatz_fuer: str | None = Field(None, description="Replacement for")
    t_ersatz_durch: str | None = Field(None, description="Replaced by")
    din: str | None = Field(None, description="Norms")
    bemerkung: str | None = Field(None, description="Remarks")
    cdb_copy_of_item_id: str | None = Field(None, description="Copy of ID")
    type_object_id: str | None = Field(None, description="BOM Type ID")
    cdb_depends_on: str | None = Field(None, description="Derived from")
    site_object_id: str | None = Field(None, description="Plant")
    cssaas_frame_add_attr_1: str | None = Field(None, description="Additional Attribute 1")
    cssaas_frame_add_attr_2: str | None = Field(None, description="Additional Attribute 2")
    cssaas_frame_add_attr_3: str | None = Field(None, description="Additional Attribute 3")
    cssaas_frame_add_attr_4: str | None = Field(None, description="Additional Attribute 4")
    cssaas_frame_add_attr_5: str | None = Field(None, description="Additional Attribute 5")
    cdb_cpersno: str | None = Field(None, description="Created by")
    cdb_cpersno_name: str | None = Field(None, description="Created by")
    cdb_cdate: datetime | None = Field(None, description="Created on")
    cdb_mpersno: str | None = Field(None, description="Last Modified by")
    cdb_mpersno_name: str | None = Field(None, description="Last Modified by")
    cdb_mdate: datetime | None = Field(None, description="Last Modified on")
    cdb_m2persno: str | None = Field(None, description="File Last Saved by")
    cdb_m2persno_name: str | None = Field(None, description="File Last Saved by")
    cdb_m2date: datetime | None = Field(None, description="File Last Saved on")
    st_durchmesser: float | None = Field(None, description="Diameter")
    st_laenge: float | None = Field(None, description="Length")
    st_hoehe: float | None = Field(None, description="Height")
    cdb_object_id: str | None = Field(None, description="Object ID")
    site_erp: str | None = Field(None, description="Plant")
    fertart: str | None = Field(None, description="Production Type")
    t_pruef_datum: datetime | None = Field(None, description="Release Date")
    oberflaeche: str | None = Field(None, description="Surface")
    mengeneinheit: str | None = Field(None, description="Unit of Measure")
    gebrauchsstand: str | None = Field(None, description="Usability")
    st_breite: float | None = Field(None, description="Width")

    # Custom Char Fields
    cca_char_1: str | None = Field(None, description="Custom Char Field")
    cca_char_2: str | None = Field(None, description="Custom Char Field")
    cca_char_3: str | None = Field(None, description="Custom Char Field")
    cca_char_4: str | None = Field(None, description="Custom Char Field")
    cca_char_5: str | None = Field(None, description="Custom Char Field")
    cca_char_6: str | None = Field(None, description="Custom Char Field")
    cca_char_7: str | None = Field(None, description="Custom Char Field")
    cca_char_8: str | None = Field(None, description="Custom Char Field")
    cca_char_9: str | None = Field(None, description="Custom Char Field")
    cca_char_10: str | None = Field(None, description="Custom Char Field")
    cca_char_11: str | None = Field(None, description="Custom Char Field")
    cca_char_12: str | None = Field(None, description="Custom Char Field")
    cca_char_13: str | None = Field(None, description="Custom Char Field")
    cca_char_14: str | None = Field(None, description="Custom Char Field")
    cca_char_15: str | None = Field(None, description="Custom Char Field")
    cca_char_16: str | None = Field(None, description="Custom Char Field")
    cca_char_17: str | None = Field(None, description="Custom Char Field")
    cca_char_18: str | None = Field(None, description="Custom Char Field")
    cca_char_19: str | None = Field(None, description="Custom Char Field")
    cca_char_20: str | None = Field(None, description="Custom Char Field")
    # Custom BigChar Fields
    cca_bigchar_part_1: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_part_2: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_part_3: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_part_4: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_part_5: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_part_6: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_part_7: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_part_8: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_part_9: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_part_10: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_part_11: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_part_12: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_part_13: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_part_14: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_part_15: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_part_16: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_part_17: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_part_18: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_part_19: str | None = Field(None, description="Custom BigChar Field")
    cca_bigchar_part_20: str | None = Field(None, description="Custom BigChar Field")
    # Custom Integer Fields
    cca_integer_part_1: int | None = Field(None, description="Custom Integer Field")
    cca_integer_part_2: int | None = Field(None, description="Custom Integer Field")
    cca_integer_part_3: int | None = Field(None, description="Custom Integer Field")
    cca_integer_part_4: int | None = Field(None, description="Custom Integer Field")
    cca_integer_part_5: int | None = Field(None, description="Custom Integer Field")
    cca_integer_part_6: int | None = Field(None, description="Custom Integer Field")
    cca_integer_part_7: int | None = Field(None, description="Custom Integer Field")
    cca_integer_part_8: int | None = Field(None, description="Custom Integer Field")
    cca_integer_part_9: int | None = Field(None, description="Custom Integer Field")
    cca_integer_part_10: int | None = Field(None, description="Custom Integer Field")
    cca_integer_part_11: int | None = Field(None, description="Custom Integer Field")
    cca_integer_part_12: int | None = Field(None, description="Custom Integer Field")
    cca_integer_part_13: int | None = Field(None, description="Custom Integer Field")
    cca_integer_part_14: int | None = Field(None, description="Custom Integer Field")
    cca_integer_part_15: int | None = Field(None, description="Custom Integer Field")
    cca_integer_part_16: int | None = Field(None, description="Custom Integer Field")
    cca_integer_part_17: int | None = Field(None, description="Custom Integer Field")
    cca_integer_part_18: int | None = Field(None, description="Custom Integer Field")
    cca_integer_part_19: int | None = Field(None, description="Custom Integer Field")
    cca_integer_part_20: int | None = Field(None, description="Custom Integer Field")
    # Custom Float Fields
    cca_float_part_1: float | None = Field(None, description="Custom Float Field")
    cca_float_part_2: float | None = Field(None, description="Custom Float Field")
    cca_float_part_3: float | None = Field(None, description="Custom Float Field")
    cca_float_part_4: float | None = Field(None, description="Custom Float Field")
    cca_float_part_5: float | None = Field(None, description="Custom Float Field")
    cca_float_part_6: float | None = Field(None, description="Custom Float Field")
    cca_float_part_7: float | None = Field(None, description="Custom Float Field")
    cca_float_part_8: float | None = Field(None, description="Custom Float Field")
    cca_float_part_9: float | None = Field(None, description="Custom Float Field")
    cca_float_part_10: float | None = Field(None, description="Custom Float Field")
    cca_float_part_11: float | None = Field(None, description="Custom Float Field")
    cca_float_part_12: float | None = Field(None, description="Custom Float Field")
    cca_float_part_13: float | None = Field(None, description="Custom Float Field")
    cca_float_part_14: float | None = Field(None, description="Custom Float Field")
    cca_float_part_15: float | None = Field(None, description="Custom Float Field")
    cca_float_part_16: float | None = Field(None, description="Custom Float Field")
    cca_float_part_17: float | None = Field(None, description="Custom Float Field")
    cca_float_part_18: float | None = Field(None, description="Custom Float Field")
    cca_float_part_19: float | None = Field(None, description="Custom Float Field")
    cca_float_part_20: float | None = Field(None, description="Custom Float Field")
    # Custom Boolean Fields
    cca_bool_part_1: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_part_2: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_part_3: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_part_4: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_part_5: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_part_6: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_part_7: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_part_8: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_part_9: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_part_10: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_part_11: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_part_12: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_part_13: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_part_14: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_part_15: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_part_16: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_part_17: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_part_18: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_part_19: bool | None = Field(None, description="Custom Boolean Field")
    cca_bool_part_20: bool | None = Field(None, description="Custom Boolean Field")
    # Custom Date Fields
    cca_date_part_1: datetime | None = Field(None, description="Custom Date Field")
    cca_date_part_2: datetime | None = Field(None, description="Custom Date Field")
    cca_date_part_3: datetime | None = Field(None, description="Custom Date Field")
    cca_date_part_4: datetime | None = Field(None, description="Custom Date Field")
    cca_date_part_5: datetime | None = Field(None, description="Custom Date Field")
    cca_date_part_6: datetime | None = Field(None, description="Custom Date Field")
    cca_date_part_7: datetime | None = Field(None, description="Custom Date Field")
    cca_date_part_8: datetime | None = Field(None, description="Custom Date Field")
    cca_date_part_9: datetime | None = Field(None, description="Custom Date Field")
    cca_date_part_10: datetime | None = Field(None, description="Custom Date Field")
    cca_date_part_11: datetime | None = Field(None, description="Custom Date Field")
    cca_date_part_12: datetime | None = Field(None, description="Custom Date Field")
    cca_date_part_13: datetime | None = Field(None, description="Custom Date Field")
    cca_date_part_14: datetime | None = Field(None, description="Custom Date Field")
    cca_date_part_15: datetime | None = Field(None, description="Custom Date Field")
    cca_date_part_16: datetime | None = Field(None, description="Custom Date Field")
    cca_date_part_17: datetime | None = Field(None, description="Custom Date Field")
    cca_date_part_18: datetime | None = Field(None, description="Custom Date Field")
    cca_date_part_19: datetime | None = Field(None, description="Custom Date Field")
    cca_date_part_20: datetime | None = Field(None, description="Custom Date Field")

    document_ids: list[str] = Field([], description="List of document IDs, that were changed. (z_nummer@z_index)")
    documents: list["Document"] = Field([], exclude=True)

    def link_objects(self, data: "EventData"):
        from .document import Document

        if self.document_ids:
            documents = get_items_of_type(data, Document)
            self._link_documents(documents)

    def _link_documents(self, documents: list["Document"]):
        for document in documents:
            if f"{document.z_nummer}@{document.z_index}" in self.document_ids and document not in self.documents:
                self.documents.append(document)


class Material(BaseObject):
    object_type: Literal[ObjectType.MATERIAL] = ObjectType.MATERIAL

    cdb_object_id: str | None = Field(None, description="Object ID")
    material_index: str | None = Field(None, description="Material Index")
    material_id: str | None = Field(None, description="Material ID")
    name_de: str | None = Field(None, description="Name DE")
    name_en: str | None = Field(None, description="Name EN")
    short_name: str | None = Field(None, description="Short Name")
    application: str | None = Field(None, description="Applications")
    remark: str | None = Field(None, description="Remarks")


class BOMItem(BaseObject):
    object_type: Literal[ObjectType.BOM_ITEM] = ObjectType.BOM_ITEM

    baugruppe: str | None = Field(None, description="Assembly")
    b_index: str | None = Field(None, description="Assembly Index")
    component_materialnr_erp: str | None = Field(None, description="Material Number ERP Component")
    netto_durchm: float | None = Field(None, description="Net. Diameter")
    netto_hoehe: float | None = Field(None, description="Net. Height")
    netto_laenge: float | None = Field(None, description="Net. Length")
    netto_breite: float | None = Field(None, description="Net. Width")
    position: int | None = Field(None, description="Position")
    menge: float | None = Field(None, description="Quantity")
    stlbemerkung: str | None = Field(None, description="Remarks")
    mengeneinheit: str | None = Field(None, description="Unit of Measure")
    teilenummer: str = Field(..., description="part number")
    t_index: str = Field(..., description="part index")
